apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  containers:
  - name: postgres
    image: postgres
    volumeMounts:
    - name: postgres-persistent-storage
      mountPath: /data/postgres
  volumes:
  - name: postgres-persistent-storage
    emptyDir: {}